server:
  port: 9090

# 메일 발송
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: amuse9418
    password: jbzfokkdstqiazke
    properties:
      mail:
        smtp:
          auth: true
          timeout: 300000
          starttls:
            enable: true